name: Node.js CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm ci

      - name: Check Code Formatting
        run: npm run format:check

      - name: Build Docker Image
        run: docker build -t node-devops .
   deploy:
  needs: build-and-test
  runs-on: ubuntu-latest

  steps:
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          cd /home/ubuntu/node-devops-test

          git pull origin master

          docker build -t node-devops .

          docker stop node-devops || true
          docker rm node-devops || true

          docker run -d \
            --name node-devops \
            -p 8080:8080 \
            node-devops
